{% set name = "happymath" %}
{% set version = "0.1.4" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/happymath/happymath-{{ version }}.tar.gz
  sha256: b28b96fa0bcc014dc4c5f11c9a1056f79edee462cf32b0e9198a6ede80fbe1b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy ==1.10.0
    - sympy
    - pandas <2.2.0
    - matplotlib-base <3.8.0
    - ipython
    - scikit-learn
    - lightgbm
    - catboost
    - xgboost
    - pycaret ==3.3.2
    - pyomo
    - pymoo
    - glpk
    - ipopt
    - coin-or-cbc
    - scip
    - py-pde
    - seaborn
    - ipykernel
    - dash
    - dash-bootstrap-components
    - timeout-decorator
    - shap
    - panel
    - watchfiles
    - jupyter_bokeh
    - umap-learn
    - statsmodels
    - patsy

test:
  imports:
    - happymath
  commands:
    - python -c "import happymath, sys; print(happymath.__version__)"
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/HappyMathLabs/happymath
  summary: "Happymath is a high-level mathematical modeling Python library that focuses on reducing users' learning costs via high-level encapsulation, enabling efficient mathematical modeling for competitions and applied mathematics."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HappymathLabs
